export const doughnuts = {
  0: {
    name: "Speculoos Sensation",
    description:
      "Caramel Filled, Caramel Icing, Speculoos Crumb & Biscuit, Chocolate & Vanilla Drizzle",
    manufacturer: "Dunkin'",
    imagePath: "./dougnut-media/dunkin/Donut-Speculoos-Sensation",
    allergens: ["Nuts", "Egg", "Milk", "Soya", "Wheat", "Sulphites"],
    kcal: 421,
  },
  1: {
    name: "Strawberry Rainbow",
    description: "Strawberry Icing and Rainbow Sprinkles",
    manufacturer: "Dunkin'",
    imagePath: "./dougnut-media/dunkin/Donut-Strawberry-Rainbow",
    allergens: ["Nuts", "Egg", "Milk", "Soya", "Wheat"],
    kcal: 275,
  },
  2: {
    name: "Rainbow Fruits",
    description:
      "Strawberry Filled, Vanilla Icing & Chewy Fruity Rainbow Candies",
    manufacturer: "Dunkin'",
    imagePath: "./dougnut-media/dunkin/Donut-Rainbow-Fruits",
    allergens: ["Nuts", "Egg", "Milk", "Soya", "Wheat"],
    kcal: 358,
  },
  3: {
    name: "Cookie Crème Blast",
    description:
      "Bavarian Crème Filled, Blue Vanilla Icing, Cookie Crumb & Biscuit, Chocolate & Vanilla Drizzle",
    manufacturer: "Dunkin'",
    imagePath: "./dougnut-media/dunkin/Donut-Cookie-Creme-Blast",
    allergens: ["Nuts", "Egg", "Milk", "Soya", "Wheat"],
    kcal: 398,
  },
  4: {
    name: "Chocolate Monster",
    description: "Chocolate Icing & Sprinkles",
    manufacturer: "Dunkin'",
    imagePath: "./dougnut-media/dunkin/Donut-Chocolate-Monster",
    allergens: ["Nuts", "Egg", "Milk", "Soya", "Wheat"],
    kcal: 299,
  },
  5: {
    name: "Chocolate Fudge Cake",
    description: "Chocolate Cake & Icing, Caramel Fudge Cubes & Drizzle",
    manufacturer: "Dunkin'",
    imagePath: "./dougnut-media/dunkin/Donut-Chocolate-Fudge-Cake",
    allergens: ["Nuts", "Egg", "Milk", "Soya", "Wheat", "Sulphites"],
    kcal: 361,
  },
  6: {
    name: "Boston Crème",
    description: "Bavarian Crème Filled & Chocolate Icing",
    manufacturer: "Dunkin'",
    imagePath: "./dougnut-media/dunkin/Donut-Boston-Creme",
    allergens: ["Nuts", "Egg", "Milk", "Soya", "Wheat"],
    kcal: 320,
  },
  7: {
    name: "Mr Happy",
    description: "Bavarian Crème Filled, Vanilla Icing & Chocolate Smile",
    manufacturer: "Dunkin'",
    imagePath: "./dougnut-media/dunkin/Donut-Mr-Happy",
    allergens: ["Nuts", "Egg", "Milk", "Soya", "Wheat"],
    kcal: 339,
  },
  8: {
    name: "Rocky Road",
    description:
      "Hazelnut Filling, Chocolate Icing & Drizzle, Marshmallows, Caramel Fudge Cubes & Biscuit Crumble",
    manufacturer: "Dunkin'",
    imagePath: "./dougnut-media/dunkin/Donut-Rocky-Road",
    allergens: ["Nuts", "Egg", "Milk", "Soya", "Wheat"],
    kcal: 409,
  },
  9: {
    name: "Original Glazed",
    description: "The Classic Glazed Donut",
    manufacturer: "Dunkin'",
    imagePath: "./dougnut-media/dunkin/Donut-Original-Glazed",
    allergens: ["Nuts", "Egg", "Milk", "Soya", "Wheat"],
    kcal: 266,
  },
};
